# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = [
    # whitespace before :
    "E203",
]
fixable = ["ALL"]

[tool.ruff.lint.isort]
combine-as-imports = true
order-by-type = true
default-section = "third-party"
section-order = [
    "future",
    "standard-library",
    "third-party",
    "dask",
    "rapids",
    "first-party",
    "local-folder",
]
known-first-party = [
    "ucxx",
    "distributed_ucxx",
]

[tool.ruff.lint.isort.sections]
dask = [
    "dask",
    "distributed",
]
rapids = [
    "rmm",
    "cudf",
]

[tool.codespell]
ignore-words-list = "cancelation,inflight"
