c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

sysroot_linux_64:
  - "2.17"

cmake:
  - ">=3.23.1,!=3.25.0"

python:
  - 3.9
  - 3.10

ucx:
  - 1.14.0

gmock:
  - ">=1.13.0"

gtest:
  - ">=1.13.0"
