c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.17"

cmake:
  - ">=3.26.4"

python:
  - 3.10
  - 3.11
  - 3.12

ucx:
  - "==1.15.*"

gmock:
  - ">=1.13.0"

gtest:
  - ">=1.13.0"

rapids_version:
  - "25.2.*"
